-- COMPROBAR CONEXION USUARIO SYSTEM
SELECT USER
FROM dual;

-- BLOQUE INSTALACION LOCAL 
ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER PRY2204_S8
IDENTIFIED BY "PRY2204.semana_8"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PRY2204_S8;

GRANT RESOURCE TO PRY2204_S8;

ALTER USER PRY2204_S8 DEFAULT ROLE RESOURCE;

-- COMPROBAR USUARIO PRY2204_S8 CREADO 
SELECT username
FROM dba_users
WHERE username = 'PRY2204_S8';

-- COMPROBAR CONEXION USUARIO PRY2204_S8
SELECT USER
FROM dual;

/*
============ CASO 1 ============ 
IMPLEMENTACION MODELO RELACIONAL
TALLER MECANICO MIKES LTDA. 
================================ */

/* 
1. TABLA PAIS
el ID comienza en 9 e incrementa en 3 mediante IDENTITY.
*/

CREATE TABLE pais (
id_pais NUMBER(3)
GENERATED BY DEFAULT AS IDENTITY
(START WITH 9 INCREMENT BY 3),

nom_pais VARCHAR2(30) NOT NULL,

CONSTRAINT pais_pk
PRIMARY KEY (id_pais)
);

/*
2. TABLA CIUDAD
*/
CREATE TABLE ciudad (
id_ciudad NUMBER(3) NOT NULL,
nom_ciudad VARCHAR2(30) NOT NULL,
cod_pais NUMBER(3) NOT NULL,

CONSTRAINT ciudad_pk
PRIMARY KEY (id_ciudad),

CONSTRAINT ciudad_fk_pais
FOREIGN KEY (cod_pais)
REFERENCES pais (id_pais)
);

/*
3. TABLA SUCURSAL
*/
CREATE TABLE sucursal (
id_sucursal CHAR(3) NOT NULL,
nom_sucursal VARCHAR2(20) NOT NULL,
calle VARCHAR2(20) NOT NULL,
num_calle NUMBER(4) NOT NULL,
cod_ciudad NUMBER(3) NOT NULL,

CONSTRAINT sucursal_pk
PRIMARY KEY (id_sucursal),

CONSTRAINT sucursal_fk_ciudad
FOREIGN KEY (cod_ciudad)
REFERENCES ciudad (id_ciudad)
);

-- VERIFICACION EL PRIMER BLOQUE DE LA TABLA 
SELECT table_name
FROM user_tables
WHERE table_name IN ('PAIS', 'CIUDAD', 'SUCURSAL')
ORDER BY table_name;

/*
4. TABLA MARCA
*/
CREATE TABLE marca (
id_marca NUMBER(2) NOT NULL,
descripcion VARCHAR2(20) NOT NULL,

CONSTRAINT marca_pk
PRIMARY KEY (id_marca)
);

/* 
5. TABLA MODELO
*/
CREATE TABLE modelo (
id_modelo NUMBER(5) NOT NULL,
marca_id NUMBER(2) NOT NULL,
descripcion VARCHAR2(20) NOT NULL,

CONSTRAINT modelo_pk
PRIMARY KEY (id_modelo, marca_id),

CONSTRAINT modelo_fk_marca
FOREIGN KEY (marca_id)
REFERENCES marca (id_marca)
);

/*
6. TABLA TIPO_AUTOMOVIL
*/
CREATE TABLE tipo_automovil (
id_tipo CHAR(3) NOT NULL,
descripcion VARCHAR2(20) NOT NULL,

CONSTRAINT tipo_automovil_pk
PRIMARY KEY (id_tipo)
);

-- VERIFICACION SEGUNDO GRUPO
SELECT table_name
FROM user_tables
WHERE table_name IN ('MARCA', 'MODELO', 'TIPO_AUTOMOVIL')
ORDER BY table_name;

/*
7. TABLA CLIENTE
*/
CREATE TABLE cliente (
rut NUMBER(8) NOT NULL,
dv CHAR(1) NOT NULL,
pnombre VARCHAR2(20) NOT NULL,
snombre VARCHAR2(20),
apaterno VARCHAR2(20) NOT NULL,
amaterno VARCHAR2(20) NOT NULL,
telefono VARCHAR2(12),
email VARCHAR2(40),
tipo_cli CHAR(1) NOT NULL,

CONSTRAINT cliente_pk
PRIMARY KEY (rut)
);

/*
8. TABLA ESTANDAR
CL_RUT es PK y tambien FK hacia CLIENTE.
*/
CREATE TABLE estandar (
cl_rut NUMBER(8) NOT NULL,
puntaje_fidelidad NUMBER(10) NOT NULL,

CONSTRAINT estandar_pk
PRIMARY KEY (cl_rut),

CONSTRAINT estandar_fk_cliente
FOREIGN KEY (cl_rut)
REFERENCES cliente (rut)
);

/*
9. TABLA PREMIUM
CL_RUT es PK y tambien FK hacia CLIENTE.
*/
CREATE TABLE premium (
cl_rut NUMBER(8) NOT NULL,
pesos_clientes NUMBER(10) NOT NULL,
monto_credito NUMBER(10),

CONSTRAINT premium_pk
PRIMARY KEY (cl_rut),

CONSTRAINT premium_fk_cliente
FOREIGN KEY (cl_rut)
REFERENCES cliente (rut)
);

-- VERIFICACION 
SELECT table_name
FROM user_tables
WHERE table_name IN ('CLIENTE', 'ESTANDAR', 'PREMIUM')
ORDER BY table_name;

/*
10. TABLA AUTOMOVIL
se relaciona con CLIENTE, MODELO y TIPO_AUTOMOVIL
*/
CREATE TABLE automovil (
patente CHAR(8) NOT NULL,
annio NUMBER(4) NOT NULL,
cant_puertas NUMBER(1) NOT NULL,
km NUMBER(6) NOT NULL,
color VARCHAR2(30) NOT NULL,
cod_tipo_auto CHAR(3) NOT NULL,
cod_modelo NUMBER(5) NOT NULL,
cod_marca NUMBER(2) NOT NULL,
cl_rut NUMBER(8) NOT NULL,

CONSTRAINT automovil_pk
PRIMARY KEY (patente),

CONSTRAINT automovil_fk_cliente
FOREIGN KEY (cl_rut)
REFERENCES cliente (rut),

CONSTRAINT automovil_fk_modelo
FOREIGN KEY (cod_modelo, cod_marca)
REFERENCES modelo (id_modelo, marca_id),

CONSTRAINT automovil_fk_tipo
FOREIGN KEY (cod_tipo_auto)
REFERENCES tipo_automovil (id_tipo)
);

-- VERIFICAR TABLA AUTOMOVIL
DESC automovil;

/*
11. TABLA MECANICO
el codigo comienza 460 e incrementa en 7.
COD_SUPERVISOR crea una relacion con la misma tabla.
*/
CREATE TABLE mecanico (
cod_mecanico NUMBER(5)
GENERATED BY DEFAULT AS IDENTITY
(START WITH 460 INCREMENT BY 7),

pnombre VARCHAR2(20) NOT NULL,
snombre VARCHAR2(20) NOT NULL,
apaterno VARCHAR2(20) NOT NULL,
amaterno VARCHAR2(20) NOT NULL,
bono_jefatura NUMBER(10),
sueldo NUMBER(10) NOT NULL,
monto_impuestos NUMBER(10) NOT NULL,
cod_supervisor NUMBER(5),

CONSTRAINT mecanico_pk
PRIMARY KEY (cod_mecanico),

CONSTRAINT mecanico_fk_mecanico
FOREIGN KEY (cod_supervisor)
REFERENCES mecanico (cod_mecanico)
);

/*
12. TABLA MANTENCION
durante el modelo original, NUM_MANTENCION es la PK.
esta PK se modificara en el CASO 2.
*/
CREATE TABLE mantencion (
num_mantencion NUMBER(4) NOT NULL,
cod_sucursal CHAR(3) NOT NULL,
fecha_ingreso DATE NOT NULL,
fecha_salida DATE,
patente_auto CHAR(8),
cod_mecanico NUMBER(5) NOT NULL,
costo_total NUMBER(7) NOT NULL,
estado VARCHAR2(15),

CONSTRAINT mantencion_pk
PRIMARY KEY (num_mantencion),

CONSTRAINT mant_fk_automovil
FOREIGN KEY (patente_auto)
REFERENCES automovil (patente),

CONSTRAINT mant_fk_mecanico
FOREIGN KEY (cod_mecanico)
REFERENCES mecanico (cod_mecanico),

CONSTRAINT mant_fk_sucursal
FOREIGN KEY (cod_sucursal)
REFERENCES sucursal (id_sucursal)
);

/*
13. TABLA SERVICIO
*/
CREATE TABLE servicio (
id_servicio NUMBER(3) NOT NULL,
descripcion VARCHAR2(100) NOT NULL,
costo NUMBER(7) NOT NULL,

CONSTRAINT servicio_pk
PRIMARY KEY (id_servicio)
);

/*
14. TABLA DETALLE_SERVICIO
modelo inicial, PK utiliza MANTENCION_NUM y COD_SERVICIO.
se modifica en el CASO 2.
*/
CREATE TABLE detalle_servicio (
mantencion_num NUMBER(4) NOT NULL,
cod_servicio NUMBER(3) NOT NULL,
descuento_serv NUMBER(4,3) NOT NULL,
cantidad NUMBER(3) NOT NULL,

CONSTRAINT detalle_servicio_pk
PRIMARY KEY (mantencion_num, cod_servicio),

CONSTRAINT det_serv_fk_mantencion
FOREIGN KEY (mantencion_num)
REFERENCES mantencion (num_mantencion),

CONSTRAINT det_serv_fk_servicio
FOREIGN KEY (cod_servicio)
REFERENCES servicio (id_servicio)
);

-- VERIFICACION EXISTENCIA 14 TABLAS
SELECT table_name
FROM user_tables
ORDER BY table_name;

/*
============ CASO 2 ============ 
MODIFICACION MODELO RELACIONAL
================================ */

/* 1. Eliminar atributos derivado COSTO_TOTAL*/

ALTER TABLE mantencion
DROP COLUMN costo_total;

/* 2. Eliminar temporalmente FK de DETALLE_SERVICIO
es necesario eliminarla antes de cambiar PK de MANTENCION 
depende de ella. */

ALTER TABLE detalle_servicio
DROP CONSTRAINT det_serv_fk_mantencion;

/* 3. Eliminiar PK original de DETALLE_SERVICIO
se cambia para incorporar COD_SUCURSAL */

ALTER TABLE detalle_servicio
DROP CONSTRAINT detalle_servicio_pk;

/* 4. Eliminar PK orginal de MANTENCION. */

ALTER TABLE mantencion
DROP CONSTRAINT mantencion_pk;

/* 5. Crear nueva PK compuesta de MANTENCION */

ALTER TABLE mantencion
ADD CONSTRAINT mantencion_pk
PRIMARY KEY (num_mantencion, cod_sucursal);

/* 6. Agregar COD_SUCURSAL a DETALLE_SERVICIO 
la tabla necesita las dos columnas que forman PK de MANTENCION
para crear la nueva FK.
*/

ALTER TABLE detalle_servicio
ADD cod_sucursal CHAR(3) NOT NULL;

/* 7. Crear nueva PK de DETALLE_SERVICIO */

ALTER TABLE detalle_servicio
ADD CONSTRAINT detalle_servicio_pk
PRIMARY KEY (
mantencion_num,
cod_sucursal,
cod_servicio
);

/* 8. Crear nueva FK compuesta hacia MANTENCION */

ALTER TABLE detalle_servicio
ADD CONSTRAINT det_serv_fk_mantencion
FOREIGN KEY (mantencion_num, cod_sucursal)
REFERENCES mantencion (num_mantencion, cod_sucursal);

/* 9. Hacer unico el EMAIL del CLIENTE 
EMAIL sigue opcional, pero no puede repetirse*/

ALTER TABLE cliente
ADD CONSTRAINT cliente_un_email
UNIQUE (email);

/* 10. Validar Digito Verificador del Rut 
se permiten numeros del 0-9 y letra K. */

ALTER TABLE cliente
ADD CONSTRAINT cliente_ck_dv
CHECK (dv IN (
    '0', '1', '2', '3', '4',
    '5', '6', '7', '8', '9', 'K'
));

/* 11. Validar SUELDO MINIMO del MECANICO 
no puede ser inferior a $510.000 */

ALTER TABLE mecanico
ADD CONSTRAINT mecanico_ck_sueldo
CHECK (sueldo >= 510000);


/* 12. Validar estado de MANTENCION
solo se permite los 4 estados indicados */

ALTER TABLE mantencion
ADD CONSTRAINT mantencion_ck_estado
CHECK (
estado IN (
'Reserva',
'Ingresado',
'Entregado',
'Anulado'
)
);

/*
============ CASO 3 ============ 
POBLAMIENTO DEL MODELO RELACIONAL
================================ */

/* 1. creacion de SECUENCIAS */

CREATE SEQUENCE seq_servicio
START WITH 400
INCREMENT BY 2
NOCYCLE
NOCACHE;

CREATE SEQUENCE seq_ciudad
START WITH 165
INCREMENT BY 5
NOCYCLE
NOCACHE;

/* 2. poblamiento de PAIS 
ID_PAIS generado mediante IDENTITY: 9, 12 y 15 */

INSERT INTO pais (nom_pais)
VALUES ('Chile');

INSERT INTO pais (nom_pais)
VALUES ('Peru');

INSERT INTO pais (nom_pais)
VALUES ('Colombia');

/* 3. poblamiento CIUDAD
ID_CIUDAD generado mediante SEQ_CIUDAD: 165, 170 y 175 */

INSERT INTO ciudad (
id_ciudad,
nom_ciudad,
cod_pais
)
VALUES (
seq_ciudad.NEXTVAL,
'Santiago',
9
);

INSERT INTO ciudad (
id_ciudad,
nom_ciudad,
cod_pais
)
VALUES (
seq_ciudad.NEXTVAL,
'Lima',
12
);

INSERT INTO ciudad (
id_ciudad,
nom_ciudad,
cod_pais
)
VALUES (
seq_ciudad.NEXTVAL,
'Bogotá',
15
);

/* 4. poblamiento SUCURSAL */

INSERT INTO sucursal (
id_sucursal,
nom_sucursal,
calle,
num_calle,
cod_ciudad
)
VALUES (
'S01',
'Providencia',
'Av. A. Varas',
234,
165
);

INSERT INTO sucursal (
id_sucursal,
nom_sucursal,
calle,
num_calle,
cod_ciudad
)
VALUES (
'S02',
'Las 4 esquinas',
'Av. Latinas',
669,
170
);

INSERT INTO sucursal (
id_sucursal,
nom_sucursal,
calle,
num_calle,
cod_ciudad
)
VALUES (
'S03',
'El Cafetero',
'Av. El Faro',
900,
175
);

/* 5. poblamiento SERVICIO
ID_SERVICIO generado mediante SEQ_SERVICIO: 400, 402, 404 y 406. */

INSERT INTO servicio (
id_servicio,
descripcion,
costo
)
VALUES (
seq_servicio.NEXTVAL,
'Cambio Luces',
45000
);

INSERT INTO servicio (
id_servicio,
descripcion,
costo
)
VALUES (
seq_servicio.NEXTVAL,
'Desabolladura',
67000
);

INSERT INTO servicio (
id_servicio,
descripcion,
costo
)
VALUES (
seq_servicio.NEXTVAL,
'Revisión Frenos',
30000
);

INSERT INTO servicio (
id_servicio,
descripcion,
costo
)
VALUES (
seq_servicio.NEXTVAL,
'Cambio Puerta Trasera',
50000
);

/* 6. poblamiento MECANICO
COD_MECANICO generado mediante IDENTITY:
460, 467, 474, 481, 488, 495, 502, 509, 516 y 523. */

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Jorge', 'Pablo', 'Soto', 'Sierpe',
5400000, 2759000, 223580, NULL
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Pedro', 'Jose', 'Manriquez', 'Corral',
NULL, 759000, 23980, NULL
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Sandra', 'Josefa', 'Letelier', 'S.',
0, 659000, 22358, 460
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Felipe', 'M.', 'Vidal', 'A.',
NULL, 759000, 23580, 460
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Jose', 'Miguel', 'Troncoso', 'B.',
NULL, 659000, 44580, 474
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Juan', 'Pablo', 'Sánchez', 'R.',
NULL, 859000, 23380, 474
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Carlos', 'Felipe', 'Soto', 'J.',
0, 597000, 23580, 474
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Alberto', 'P.', 'Cerda', 'Ramírez',
NULL, 559000, 22380, 460
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Alejandra', 'Gabriela', 'Infanti', 'R.',
NULL, 659000, 22380, 460
);

INSERT INTO mecanico (
pnombre, snombre, apaterno, amaterno,
bono_jefatura, sueldo, monto_impuestos, cod_supervisor
)
VALUES (
'Roberto', 'Patricio', 'Gutierrez', 'Sosa',
NULL, 859000, 22380, 460
);

/* 7. poblamiento MANTENCION */

INSERT INTO mantencion (
num_mantencion,
cod_sucursal,
fecha_ingreso,
fecha_salida,
patente_auto,
cod_mecanico,
estado
)
VALUES (
101,
'S01',
TO_DATE('12-04-2023', 'DD-MM-YYYY'),
NULL,
NULL,
481,
'Reserva'
);

INSERT INTO mantencion (
num_mantencion,
cod_sucursal,
fecha_ingreso,
fecha_salida,
patente_auto,
cod_mecanico,
estado
)
VALUES (
102,
'S02',
TO_DATE('21-02-2023', 'DD-MM-YYYY'),
TO_DATE('21-02-2023', 'DD-MM-YYYY'),
NULL,
502,
'Entregado'
);

INSERT INTO mantencion (
num_mantencion,
cod_sucursal,
fecha_ingreso,
fecha_salida,
patente_auto,
cod_mecanico,
estado
)
VALUES (
103,
'S02',
TO_DATE('09-10-2023', 'DD-MM-YYYY'),
NULL,
NULL,
502,
'Anulado'
);

INSERT INTO mantencion (
num_mantencion,
cod_sucursal,
fecha_ingreso,
fecha_salida,
patente_auto,
cod_mecanico,
estado
)
VALUES (
104,
'S03',
TO_DATE('11-08-2023', 'DD-MM-YYYY'),
TO_DATE('18-08-2023', 'DD-MM-YYYY'),
NULL,
509,
'Entregado'
);

INSERT INTO mantencion (
num_mantencion,
cod_sucursal,
fecha_ingreso,
fecha_salida,
patente_auto,
cod_mecanico,
estado
)
VALUES (
105,
'S03',
TO_DATE('03-12-2023', 'DD-MM-YYYY'),
NULL,
NULL,
509,
'Ingresado'
);

/* 8. confirmar TRANSACCION */

COMMIT;

-- VERIFICACION DEL POBLAMIENTO 
SELECT id_pais, nom_pais
FROM pais
ORDER BY id_pais;

SELECT id_ciudad,
nom_ciudad,
cod_pais
FROM ciudad
ORDER BY id_ciudad;

SELECT id_sucursal,
nom_sucursal,
calle,
num_calle,
cod_ciudad
FROM sucursal
ORDER BY id_sucursal;

SELECT id_servicio,
descripcion,
costo
FROM servicio
ORDER BY id_servicio;

SELECT cod_mecanico,
pnombre,
snombre,
apaterno,
amaterno,
bono_jefatura,
sueldo,
monto_impuestos,
cod_supervisor
FROM mecanico
ORDER BY cod_mecanico;

SELECT num_mantencion,
cod_sucursal,
TO_CHAR(fecha_ingreso, 'DD-MM-YYYY') AS fecha_ingreso,
TO_CHAR(fecha_salida, 'DD-MM-YYYY') AS fecha_salida,
patente_auto,
cod_mecanico,
estado
FROM mantencion
ORDER BY num_mantencion;

/*
============ CASO 4 ============ 
RECUPERACION DE DATOS
================================ */

/*
=============================================
INFORME 1

simulacion rebaja impuestos para mecanicos:
- bono jafatura nulo.
- impuesto inferiores a $40.000.
- rebaja impuesto al 80% del valor actual.
=============================================
*/

SELECT cod_mecanico AS "ID MECANICO",

pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
sueldo AS "SALARIO",
monto_impuestos AS "IMPUESTO ACTUAL",
monto_impuestos * 0.80 AS "IMPUESTO REBAJADO",
sueldo - (monto_impuestos * 0.80) AS "SUELDO CON REBAJA IMPUESTOS"

FROM mecanico
WHERE bono_jefatura IS NULL AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;

/*
=============================================
INFORME 2

simulacion reajuste salarial:
- mecanicos con sueldo entre $600.000 y $900.000.
- 0 mecanicos sin supervisor.
- reajuste correspondiente al 5% del sueldo.
=============================================
*/

SELECT cod_mecanico AS "IDENTIFICADOR",

pnombre || ' ' || snombre || ' ' || apaterno AS "MECANICO",
sueldo AS "SALARIO ACTUAL",
sueldo * 0.05 AS "AJUSTE",
sueldo + (sueldo * 0.05) AS "SUELDO_REAJUSTADO"

FROM mecanico
WHERE (sueldo BETWEEN 600000 AND 900000) OR (cod_supervisor IS NULL)
ORDER BY sueldo ASC, pnombre || ' ' || snombre || ' ' || apaterno DESC;

