/* 
============================================
 FASE 3 - IMPLEMENTACION MODELO FISICO ANFP
============================================
*/

/*
==============================================
 BLOQUE DE LIMPIEZA 
 No ejecutar en un usuario nuevo.
 Ejecutar solamente si las tablas ya existen.

DROP TABLE region CASCADE CONSTRAINTS;
DROP TABLE nacionalidad CASCADE CONSTRAINTS;
DROP TABLE asociacion CASCADE CONSTRAINTS;
DROP TABLE escuela_futbol CASCADE CONSTRAINTS;
DROP TABLE idioma CASCADE CONSTRAINTS;
DROP TABLE club_futbol CASCADE CONSTRAINTS;
DROP TABLE comuna CASCADE CONSTRAINTS;
DROP TABLE trabajador CASCADE CONSTRAINTS;
DROP TABLE jugador_futbol CASCADE CONSTRAINTS;
DROP TABLE personal_planta CASCADE CONSTRAINTS;
DROP TABLE contrato CASCADE CONSTRAINTS;
DROP TABLE jugador_idioma CASCADE CONSTRAINTS;
DROP SEQUENCE seq_club_futbol;
==============================================
*/

/*
======================================
 DDL: CREACION DE LA ESTRUCTURA
 1. Creacion de tablas padres sin FK.
======================================
*/

-- TABLA REGION.
CREATE TABLE region (
id_region     NUMBER(2),
nombre_region VARCHAR2(60) NOT NULL,

CONSTRAINT pk_region
PRIMARY KEY (id_region)
);

-- TABLA NACIONALIDAD.
CREATE TABLE nacionalidad (
id_nacionalidad NUMBER
GENERATED BY DEFAULT AS IDENTITY (START WITH 210 INCREMENT BY 2),
descripcion VARCHAR2(30) NOT NULL,

CONSTRAINT pk_nacionalidad
PRIMARY KEY (id_nacionalidad)
);

-- TABLA ASOCIACION.
CREATE TABLE asociacion (
id_asociacion       NUMBER(3),
nombre_asociacion   VARCHAR2(80) NOT NULL,
fecha_creacion      DATE NOT NULL,
tipo_asociacion     CHAR(1) NOT NULL,

CONSTRAINT pk_asociacion
PRIMARY KEY (id_asociacion),

CONSTRAINT ck_asociacion_fecha
CHECK (fecha_creacion >= DATE '1980-12-31'),

CONSTRAINT ck_asociacion_tipo
CHECK (tipo_asociacion IN ('P', 'A'))
);

-- TABLA ESCUELA_FUTBOL.
CREATE TABLE escuela_futbol (
id_escuela       NUMBER(4),
nombre_escuela   VARCHAR2(60) NOT NULL,
capacidad        NUMBER(5) NOT NULL,
fecha_fundacion  DATE NOT NULL,

CONSTRAINT pk_escuela_futbol
PRIMARY KEY (id_escuela)
);

-- TABLA IDIOMA.
CREATE TABLE idioma (
id_idioma       NUMBER(3),
nombre_idioma   VARCHAR2(30) NOT NULL,

CONSTRAINT pk_idioma
PRIMARY KEY (id_idioma)
);

-- TABLA CLUB_FUTBOL.
CREATE TABLE club_futbol (
id_club          NUMBER(3),
nombre_club      VARCHAR2(60) NOT NULL,
patrimonio       NUMBER(12) NOT NULL,
ubicacion_calle  VARCHAR2(100) NOT NULL,

CONSTRAINT pk_club_futbol
PRIMARY KEY (id_club),

CONSTRAINT un_club_futbol_nombre
UNIQUE (nombre_club)
);

/*
==============================================
 DDL: MODIFICACION
 2. Modificar una tabla mediante ALTER TABLE.
==============================================
*/

ALTER TABLE club_futbol
ADD tipo_club VARCHAR2(15)
DEFAULT 'Profesional'
NOT NULL;

/*
=====================================
 3. Creacion de tablas dependientes.
=====================================
*/

-- TABLA COMUNA.
CREATE TABLE comuna (
id_comuna      NUMBER(3),
id_region      NUMBER(2) NOT NULL,
nombre_comuna  VARCHAR2(40) NOT NULL,

CONSTRAINT pk_comuna
PRIMARY KEY (id_comuna),

CONSTRAINT fk_comuna_region
FOREIGN KEY (id_region)
REFERENCES region (id_region)
);

-- TABLA TRABAJADOR.
CREATE TABLE trabajador (
codigo_inscripcion  NUMBER(10),
rut                 NUMBER(8) NOT NULL,
digito_verificador  CHAR(1) NOT NULL,
nombres             VARCHAR2(50) NOT NULL,
apellidos           VARCHAR2(60) NOT NULL,
sueldo_base         NUMBER(10) NOT NULL,
fecha_nacimiento    DATE NOT NULL,
genero              CHAR(1) NOT NULL,
estado_civil        VARCHAR2(20) NOT NULL,
telefono_movil      VARCHAR2(15) NOT NULL,
direccion           VARCHAR2(100) NOT NULL,
email               VARCHAR2(80),
id_comuna           NUMBER(3) NOT NULL,
id_nacionalidad     NUMBER NOT NULL,

CONSTRAINT pk_trabajador
PRIMARY KEY (codigo_inscripcion),

CONSTRAINT un_trabajador_rut
UNIQUE (rut),

CONSTRAINT fk_trabajador_comuna
FOREIGN KEY (id_comuna)
REFERENCES comuna (id_comuna),

CONSTRAINT fk_trabajador_nacionalidad
FOREIGN KEY (id_nacionalidad)
REFERENCES nacionalidad (id_nacionalidad)
);

-- TABLA JUGADOR_FUTBOL.
CREATE TABLE jugador_futbol (
codigo_inscripcion       NUMBER(10),
id_asociacion            NUMBER(3) NOT NULL,
id_escuela               NUMBER(4),
puesto_campo             VARCHAR2(30) NOT NULL,
monto_total_premios      NUMBER(12) NOT NULL,
anio_dejo_amateurismo    NUMBER(4),

CONSTRAINT pk_jugador_futbol
PRIMARY KEY (codigo_inscripcion),

CONSTRAINT fk_jugador_trabajador
FOREIGN KEY (codigo_inscripcion)
REFERENCES trabajador (codigo_inscripcion),

CONSTRAINT fk_jugador_asociacion
FOREIGN KEY (id_asociacion)
REFERENCES asociacion (id_asociacion),

CONSTRAINT fk_jugador_escuela
FOREIGN KEY (id_escuela)
REFERENCES escuela_futbol (id_escuela)
);

-- TABLA PERSONAL_PLANTA.
CREATE TABLE personal_planta (
codigo_inscripcion        NUMBER(10),
id_club                   NUMBER(3) NOT NULL,
cantidad_horas_trabajadas NUMBER(5),
valor_horas_extras        NUMBER(10),

CONSTRAINT pk_personal_planta
PRIMARY KEY (codigo_inscripcion),

CONSTRAINT fk_personal_trabajador
FOREIGN KEY (codigo_inscripcion)
REFERENCES trabajador (codigo_inscripcion),

CONSTRAINT fk_personal_club
FOREIGN KEY (id_club)
REFERENCES club_futbol (id_club)
);

-- TABLA CONTRATO.
CREATE TABLE contrato (
codigo_inscripcion  NUMBER(10),
id_club             NUMBER(3),
fecha_inicio        DATE,
fecha_termino       DATE,

CONSTRAINT pk_contrato
PRIMARY KEY (
codigo_inscripcion,
id_club,
fecha_inicio
),

CONSTRAINT fk_contrato_jugador
FOREIGN KEY (codigo_inscripcion)
REFERENCES jugador_futbol (codigo_inscripcion),

CONSTRAINT fk_contrato_club
FOREIGN KEY (id_club)
REFERENCES club_futbol (id_club)
);

-- TABLA JUGADOR_IDIOMA.
CREATE TABLE jugador_idioma (
codigo_inscripcion  NUMBER(10),
id_idioma           NUMBER(3),
nivel_dominio       VARCHAR2(20) NOT NULL,

CONSTRAINT pk_jugador_idioma
PRIMARY KEY (
codigo_inscripcion,
id_idioma
),

CONSTRAINT fk_jug_idioma_jugador
FOREIGN KEY (codigo_inscripcion)
REFERENCES jugador_futbol (codigo_inscripcion),

CONSTRAINT fk_jug_idioma_idioma
FOREIGN KEY (id_idioma)
REFERENCES idioma (id_idioma)
);

/*
===========================
 DDL: SECUENCIA
 4. Secuencia CLUB_FUTBOL.
===========================
*/

CREATE SEQUENCE seq_club_futbol
START WITH 703
INCREMENT BY 4
NOCYCLE;

/*
========================
 DML: POBLAMIENTO
 5. Poblamiento REGION.
========================
*/

INSERT INTO region (id_region, nombre_region)
VALUES (1, 'ARICA Y PARINACOTA Y TARAPACA');

INSERT INTO region (id_region, nombre_region)
VALUES (2, 'ANTOFAGASTA');

INSERT INTO region (id_region, nombre_region)
VALUES (3, 'ATACAMA Y COQUIMBO');

INSERT INTO region (id_region, nombre_region)
VALUES (5, 'VALPARAISO');

INSERT INTO region (id_region, nombre_region)
VALUES (8, 'BIOBIO');

INSERT INTO region (id_region, nombre_region)
VALUES (13, 'METROPOLITANA');

INSERT INTO region (id_region, nombre_region)
VALUES (16, 'NIUBLE');

-- 6. poblamiento COMUNA.
INSERT INTO comuna (id_comuna, id_region, nombre_comuna)
VALUES (101, 13, 'SANTIAGO');

INSERT INTO comuna (id_comuna, id_region, nombre_comuna)
VALUES (102, 5, 'VALPARAISO');

INSERT INTO comuna (id_comuna, id_region, nombre_comuna)
VALUES (103, 8, 'CONCEPCION');

INSERT INTO comuna (id_comuna, id_region, nombre_comuna)
VALUES (104, 2, 'ANTOFAGASTA');

INSERT INTO comuna (id_comuna, id_region, nombre_comuna)
VALUES (105, 16, 'CHILLAN');

-- 7. poblamiento ASOCIACION.
INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(25, 'Asociacion de Futbol de Santiago',
TO_DATE('15-05-2001', 'DD-MM-YYYY'), 'P');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(26, 'Asociacion Nacional de Futbol Amateur',
TO_DATE('10-03-1998', 'DD-MM-YYYY'), 'A');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(27, 'Asociacion de Futbol de Valparaiso',
TO_DATE('21-07-1987', 'DD-MM-YYYY'), 'P');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(28, 'Asociacion de Futbol de Concepcion',
TO_DATE('30-11-1995', 'DD-MM-YYYY'), 'A');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(29, 'Asociacion de Futbol de Antofagasta',
TO_DATE('25-06-2003', 'DD-MM-YYYY'), 'P');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(30, 'Asociacion de Futbol de Temuco',
TO_DATE('12-01-2010', 'DD-MM-YYYY'), 'A');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(31, 'Asociacion de Futbol de Rancagua',
TO_DATE('08-09-1999', 'DD-MM-YYYY'), 'P');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(32, 'Asociacion de Futbol de Puerto Montt',
TO_DATE('20-04-2005', 'DD-MM-YYYY'), 'A');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(33, 'Asociacion de Futbol de La Serena',
TO_DATE('14-08-2012', 'DD-MM-YYYY'), 'P');

INSERT INTO asociacion
(id_asociacion, nombre_asociacion, fecha_creacion, tipo_asociacion)
VALUES
(34, 'Asociacion de Futbol de Chillan',
TO_DATE('01-12-2018', 'DD-MM-YYYY'), 'A');

-- 8. poblamiento NACIONALIDAD.
/* IDENTITY: 210, 212, 214, 216 y 218 */
INSERT INTO nacionalidad (descripcion)
VALUES ('Chilena');

INSERT INTO nacionalidad (descripcion)
VALUES ('Argentina');

INSERT INTO nacionalidad (descripcion)
VALUES ('Peruana');

INSERT INTO nacionalidad (descripcion)
VALUES ('Boliviana');

INSERT INTO nacionalidad (descripcion)
VALUES ('Brasilenia');

-- 9. poblamiento CLUB_FUTBOL.
/* Secuencia: 703, 707, 711, 715 y 719 */
INSERT INTO club_futbol
(id_club, nombre_club, patrimonio, ubicacion_calle, tipo_club)
VALUES
(seq_club_futbol.NEXTVAL,
'Colo-Colo',
500000000,
'Av. Marathon 5300',
'Profesional');

INSERT INTO club_futbol
(id_club, nombre_club, patrimonio, ubicacion_calle, tipo_club)
VALUES
(seq_club_futbol.NEXTVAL,
'Universidad de Chile',
450000000,
'Av. El Parron 0931',
'Profesional');

INSERT INTO club_futbol
(id_club, nombre_club, patrimonio, ubicacion_calle, tipo_club)
VALUES
(seq_club_futbol.NEXTVAL,
'Deportes Antofagasta',
180000000,
'Av. Angamos 01606',
'Profesional');

INSERT INTO club_futbol
(id_club, nombre_club, patrimonio, ubicacion_calle, tipo_club)
VALUES
(seq_club_futbol.NEXTVAL,
'Huachipato',
220000000,
'Av. Desiderio Garcia 909',
'Profesional');

INSERT INTO club_futbol
(id_club, nombre_club, patrimonio, ubicacion_calle, tipo_club)
VALUES
(seq_club_futbol.NEXTVAL,
'Niublense',
170000000,
'Av. Pedro Aguirre Cerda 1003',
'Profesional');

-- 10. confirmar los INSERT
COMMIT;

/* 
=================================
 FASE 4 - RECUPERACION DE DATOS.
=================================
*/

-- INFORME 1 - ASOCIACIONES DE FUTBOL PROFESIONAL.
SELECT 'ID:' || id_asociacion || ' * ' ||
nombre_asociacion AS asociacion,

TO_CHAR(fecha_creacion, 'DD-MM-YYYY') AS creada,
tipo_asociacion AS tipo

FROM asociacion

WHERE tipo_asociacion = 'P'
AND fecha_creacion >
TO_DATE('31-12-2000', 'DD-MM-YYYY')

ORDER BY fecha_creacion DESC;

-- INFORME 2 - PATRIMONIO DE CLUBES DE FUTBOL.
SELECT id_club AS club,
nombre_club AS "NOMBRE CLUB",
patrimonio AS "PATRIMONIO EN PESOS",
patrimonio / 955 AS "PATRIMONIO EN DOLARES"

FROM club_futbol
WHERE UPPER(nombre_club) LIKE '%A%'
AND patrimonio > 200000000
AND tipo_club = 'Profesional'

ORDER BY id_club DESC;
